### ISSUE TITLE
Emulated FPU seems to be broken on aarch64 (arm64) build

### ISSUE THREAD

**Issue by demitrios** [cebix/macemu#238]
Using the @SegHaxx fork, [macemu-flatpak](/SegHaxx/macemu-flatpak):
* compiled on a Pinebook Pro (Debian Bullseye, arm64)
  * with libraries libgtk2-dev and libsdl2-dev installed
  ```
   NO_CONFIGURE=1 ./autogen.sh
   ./configure
   make
   ``` 
* running Basilisk on the Pinebook Pro with a Mac OS 8.1 system disk and Quadra 650 rom.
  * cpu choices, 68020 and 68030, work well
  * __cpu choices, 68020+FPU, 68030+FPU, and 68040, _appear_ to work, but the mac's window sliders do not display or function properly.__ No other issues are immediately apparent.

* performing the same test on an HP laptop (Debian Bullseye, amd64), Basilisk compiled identically, and using the same Mac system disk image, rom file, and Basilisk preferences
  * all cpu choices work well 

So some issue related to the FPU emulation shows up in the aarch64 (arm64) build. The configuration script selects ieee fpe for both arm64 and amd64 builds (actually, all of the reported configuration parameters match), but Basilisk behaves differently for the different architectures. Compiling Basilisk with different `--enable-fpe` options did not change the results.

> As an aside, the emulated mac os 8.1 on the Pinebook Pro is quite fast (much faster than the original mac) and very usable -- I mostly use old archive tools and applications to convert old documents, and also access some old FileMaker databases. Printing through the AdobePS driver to a file on a shared unix volume works well, too.

**Comment by SegHaxx** [comment]
Sorry been busy with other stuff. I'd heard there was an FPU problem but hadn't seen specifics. My nostalgia is for System 7.6 which doesn't seem to hit the FPU problem. So that's one workaround?

The kanjitalk fork has been working on porting to the Apple M1, last I checked in they chose fix this by merging in a newer version of the UAE cpu core. Unfortunately they're only concerned with OSX, and thus only did this for the Xcode project and left the other builds with the old core.

I guess the real fix is getting the new UAE core merged into the Linux build, which means dealing with autotools and... ugh. So I haven't gotten around to that. :(

**Comment by SegHaxx** [comment]
Okay can confirm, built current kanjitalk755 repo on Linux aarch64, and the scrollbar problem in Mac OS 8.1 appears fixed.

I'll update my tree and make a new flatpak release in the next week or two.

**Comment by demitrios** [comment]
Yes, seems to work. Thank you.
